title: Max Florentin
author: GitHub User
email: macsee13@gmail.com
description: >
  Data Engineering Blog.
show_excerpts: true

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Max Florentin
  tagline: DataOps, Data Engineer & DevOps
  date_format: "%b %-d, %Y"
  sitemap: true
  search: true
  dark_mode: true
  portfolio_image: "assets/max-profile.jpg"
  html_lang: "en"
  condensed_mobile:
    #- home
    - page
    - post
  
  social_links:
    github:  maxflorentin
    linkedIn: in/florentin-m
    #telegram: jekyll
    #email: jekyll

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
#- cv.md


remote_theme: samarsault/plainwhite-jekyll

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
